'use strict';
/**
 * آلة حالات الرحلة — الخادم هو المصدر الوحيد للحقيقة.
 * أي انتقال غير مسموح يُرفض حتى لو أرسله التطبيق.
 */
const STATUS = {
  REQUESTED: 'REQUESTED',
  SEARCHING: 'SEARCHING',
  DRIVER_ASSIGNED: 'DRIVER_ASSIGNED',
  DRIVER_ACCEPTED: 'DRIVER_ACCEPTED',
  DRIVER_ARRIVING: 'DRIVER_ARRIVING',
  DRIVER_ARRIVED: 'DRIVER_ARRIVED',
  TRIP_STARTED: 'TRIP_STARTED',
  TRIP_COMPLETED: 'TRIP_COMPLETED',
  CANCELLED_BY_CUSTOMER: 'CANCELLED_BY_CUSTOMER',
  CANCELLED_BY_DRIVER: 'CANCELLED_BY_DRIVER',
  CANCELLED_BY_SYSTEM: 'CANCELLED_BY_SYSTEM',
  NO_DRIVER_FOUND: 'NO_DRIVER_FOUND',
};

const TRANSITIONS = {
  REQUESTED:       ['SEARCHING', 'CANCELLED_BY_CUSTOMER', 'CANCELLED_BY_SYSTEM'],
  SEARCHING:       ['DRIVER_ASSIGNED', 'NO_DRIVER_FOUND', 'CANCELLED_BY_CUSTOMER', 'CANCELLED_BY_SYSTEM'],
  DRIVER_ASSIGNED: ['DRIVER_ACCEPTED', 'SEARCHING', 'CANCELLED_BY_CUSTOMER', 'CANCELLED_BY_DRIVER', 'CANCELLED_BY_SYSTEM'],
  // «SEARCHING» هنا تعني: الكابتن اعتذر قبل الانطلاق، فنبحث للعميل عن بديل تلقائياً
  DRIVER_ACCEPTED: ['DRIVER_ARRIVING', 'SEARCHING', 'CANCELLED_BY_CUSTOMER', 'CANCELLED_BY_DRIVER', 'CANCELLED_BY_SYSTEM'],
  DRIVER_ARRIVING: ['DRIVER_ARRIVED', 'SEARCHING', 'CANCELLED_BY_CUSTOMER', 'CANCELLED_BY_DRIVER', 'CANCELLED_BY_SYSTEM'],
  DRIVER_ARRIVED:  ['TRIP_STARTED', 'SEARCHING', 'CANCELLED_BY_CUSTOMER', 'CANCELLED_BY_DRIVER', 'CANCELLED_BY_SYSTEM'],
  TRIP_STARTED:    ['TRIP_COMPLETED', 'CANCELLED_BY_SYSTEM'],
  TRIP_COMPLETED:  [],
  CANCELLED_BY_CUSTOMER: [],
  CANCELLED_BY_DRIVER:   [],
  CANCELLED_BY_SYSTEM:   [],
  NO_DRIVER_FOUND:       [],
};

const ACTIVE = new Set([
  STATUS.REQUESTED, STATUS.SEARCHING, STATUS.DRIVER_ASSIGNED, STATUS.DRIVER_ACCEPTED,
  STATUS.DRIVER_ARRIVING, STATUS.DRIVER_ARRIVED, STATUS.TRIP_STARTED,
]);

const TERMINAL = new Set([
  STATUS.TRIP_COMPLETED, STATUS.CANCELLED_BY_CUSTOMER, STATUS.CANCELLED_BY_DRIVER,
  STATUS.CANCELLED_BY_SYSTEM, STATUS.NO_DRIVER_FOUND,
]);

const canTransition = (from, to) => Array.isArray(TRANSITIONS[from]) && TRANSITIONS[from].includes(to);
const isActive = (s) => ACTIVE.has(s);
const isTerminal = (s) => TERMINAL.has(s);

const LABEL_AR = {
  REQUESTED: 'تم إرسال الطلب',
  SEARCHING: 'جاري البحث عن كابتن',
  DRIVER_ASSIGNED: 'تم إسناد الرحلة لكابتن',
  DRIVER_ACCEPTED: 'الكابتن قبل الرحلة',
  DRIVER_ARRIVING: 'الكابتن في الطريق إليك',
  DRIVER_ARRIVED: 'الكابتن وصل',
  TRIP_STARTED: 'الرحلة جارية',
  TRIP_COMPLETED: 'انتهت الرحلة',
  CANCELLED_BY_CUSTOMER: 'ألغيت من قِبلك',
  CANCELLED_BY_DRIVER: 'ألغاها الكابتن',
  CANCELLED_BY_SYSTEM: 'ألغيت من النظام',
  NO_DRIVER_FOUND: 'لا يوجد كابتن متاح',
};

module.exports = { STATUS, TRANSITIONS, canTransition, isActive, isTerminal, LABEL_AR, ACTIVE, TERMINAL };
